# -*- coding: utf-8 -*-
"""E-waste Monitoring System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PXxoRyynG91qYuBGzVEo2x2GvDzxqITr
"""

from datetime import datetime, timedelta

class E_WasteItem:
    def __init__(self, name, purchase_date, lifespan_years):
        self.name = name
        self.purchase_date = datetime.strptime(purchase_date, "%Y-%m-%d")
        self.lifespan_years = lifespan_years
        self.expiry_date = self.purchase_date + timedelta(days=lifespan_years * 365)
        self.status = "in use"

    def check_status(self):
        today = datetime.now()
        if today >= self.expiry_date and self.status == "in use":
            self.status = "due for recycling"
        return f"{self.name} is {self.status}."

    def recycle_item(self):
        if self.status == "due for recycling":
            self.status = "recycled"
            return f"{self.name} has been recycled."
        else:
            return f"{self.name} is not due for recycling yet."

def add_item(items):
    name = input("Enter item name: ")
    purchase_date = input("Enter purchase date (YYYY-MM-DD): ")
    lifespan_years = int(input("Enter expected lifespan (years): "))
    item = E_WasteItem(name, purchase_date, lifespan_years)
    items.append(item)
    print(f"{name} added successfully!")

def check_item_status(items):
    if items:
        for item in items:
            print(item.check_status())
    else:
        print("No items to check.")

def recycle_items(items):
    if items:
        for item in items:
            print(item.recycle_item())
    else:
        print("No items to recycle.")

def remove_item(items):
    if items:
        name = input("Enter the name of the item to remove: ")
        for item in items:
            if item.name == name:
                items.remove(item)
                print(f"{name} removed successfully!")
                return
        print(f"Item '{name}' not found.")
    else:
        print("No items to remove.")

def main():
    items = []
    while True:
        print("\n--- E-waste Monitoring System ---")
        print("1. Add Electronic Item")
        print("2. Check Item Status")
        print("3. Recycle Due Items")
        print("4. Remove an Item")
        print("5. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            add_item(items)
        elif choice == '2':
            check_item_status(items)
        elif choice == '3':
            recycle_items(items)
        elif choice == '4':
            remove_item(items)
        elif choice == '5':
            print("Exiting...")
            break
        else:
            print("Invalid choice, please try again.")

if __name__ == "__main__":
    main()